#Константы пользователей
MAX_EMAIL_LENGTH = 254
MAX_USERNAME_LENGTH = 150
MAX_FIRSNAME_LENGTH = 150
MAX_LASTNAME_LENGTH = 150

#Константы рецептов
MAX_NAME_TAG_LENGTH = 32
MAX_SLUG_TAG_LENGTH = 32
MAX_NAME_INGREDIENT_LENGTH = 128
MAX_UNIT_LENGTH = 64
MAX_NAME_RECIPE_LENGTH = 256
MIN_TIME_COOKING = 1
MIN_AMOUNT_INGREDIENTS = 1
